### ISSUE TITLE
Found two props that crashes the game

### ISSUE THREAD

**Issue by imendezr** [user-grinch/Project-Props#3]
The props are:
19262 - sign_speedbump 
19311 - gas_rack

Whenever I enter an area with those props the game freezes. Also happens if I try to view them in Map Editor

**Comment by PRinceBhai** [comment]
@user-grinch Have you removed this models from the files_src folder? Because I seem to get the error of these models being requested in these ID ranges. Tried them both on a New Game and a Current Play through save.

**Comment by user-grinch** [comment]
Looks like those were, removed. I'll do a quick patch. Try the master branch and lemme know if it fixes it.
